development:
  adapter: postgresql
  encoding: unicode
  database: ocill
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: s@wchyN12	

test: &test
  adapter: postgresql
  encoding: unicode
  database: ocill-test
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: s@wchyN12	

production:
  adapter: postgresql
  encoding: unicode
  database: ocill-prod
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: s@wchyN12	

cucumber:
  <<: *test