# skin: default
# theme: advanced
# theme_advanced_toolbar_location: top
# theme_advanced_toolbar_align: left
# theme_advanced_statusbar_location: bottom
# theme_advanced_buttons1: "bold,italic,strikethrough,underline,|,bullist,numlist,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,styleselect,|,pastetext,pasteword,|,outdent,indent,|,undo,redo,|,link,unlink,|,code,uploadimage"
# theme_advanced_toolbar_location: "external"
# theme_advanced_resizing: true
# theme_advanced_path: true
# theme_advanced_resize_horizontal: false
# theme_advanced_resize_vertical: true
# theme_advanced_resizing_use_cookie: true
# uploadimage_default_img_class: mce-upload-image
extended_valid_elements:
  - "iframe[src|title|width|height|allowfullscreen|frameborder]"
  - "embed[width|height|name|flashvars|src|bgcolor|align|play|loop|quality|allowscriptaccess|type|pluginspage]"
style_formats:
  - title: R-to-L
    block: div
    classes: rtl
  - title: Video
    block: div
    classes: video-player
# content_css: "https://s3.amazonaws.com/ocill-bucket/public/content.css"
plugins:
  - media
  - image
  - link
  - paste
  - textcolor
  - table
toolbar:
  - "bold,
    italic,
    strikethrough,
    underline,
    forecolor,
    backcolor, 
    |,
    bullist,
    numlist,
    |,
    justifyleft,
    justifycenter,
    justifyright,
    justifyfull,
    |,
    formatselect,
    styleselect,
    |,
    outdent,
    indent"
  - "pastetext,
    pasteword,
    |,
    undo,
    redo,
    |,
    link,
    unlink,
    |,
    image"
media_strict: false
mode: textareas